"""initial_schema

Revision ID: b558c2d2cfc6
Revises: 
Create Date: 2026-07-11 11:46:40.217303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b558c2d2cfc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('minimum_vram_gb', sa.Float(), nullable=False),
    sa.Column('recommended_vram_gb', sa.Float(), nullable=False),
    sa.Column('supports_quantization', sa.Boolean(), nullable=False),
    sa.Column('supports_cpu_offload', sa.Boolean(), nullable=False),
    sa.Column('supports_lora', sa.Boolean(), nullable=False),
    sa.Column('max_resolution_width', sa.Integer(), nullable=False),
    sa.Column('max_resolution_height', sa.Integer(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_fps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('avg_inference_time_seconds', sa.Float(), nullable=True),
    sa.Column('avg_vram_usage_gb', sa.Float(), nullable=True),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('output_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('queue_time_seconds', sa.Float(), nullable=True),
    sa.Column('load_model_time_seconds', sa.Float(), nullable=True),
    sa.Column('inference_time_seconds', sa.Float(), nullable=True),
    sa.Column('postprocess_time_seconds', sa.Float(), nullable=True),
    sa.Column('total_time_seconds', sa.Float(), nullable=True),
    sa.Column('peak_vram_gb', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
